export const ADD_NEW_TIMER = "ADD_NEW_TIMER";
export const REMOVE_TIMER_BY_ID = "REMOVE_TIMER_BY_ID";
export const REMOVE_TIMER_BY_INDEX = "REMOVE_TIMER_BY_INDEX";
export const EDIT_TIMER_BY_ID = "EDIT_TIMER_BY_ID";
export const EDIT_TIMER_BY_INDEX = "EDIT_TIMER_BY_INDEX";
